[package]
name = "vcs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap =  { version = "4.*", features = ["derive"] }
sha1 = "0.10.5"
walkdir = "2.3.2"
json = "0.12.4"
chrono = "0.4.22"
serde = {version = "1.0", features = ["derive"]}
serde_derive = "1.0"
serde_json = "1.0"
